services:
  mysql:
    image: mysql:8.4
    container_name: ofmysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_SHIELD_DATABASE:-shield}
      MYSQL_USER: ${MYSQL_USER:-mysql_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql_password}
    volumes:
      - of_mysql_data:/var/lib/mysql
    networks:
      - db_network
    expose:
      - "3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10

  iframe:
    container_name: iframe
    platform: linux/amd64
    volumes:
      - ./iframe/iframe_nginx.conf:/etc/nginx/conf.d/default.conf
    image: ghcr.io/openfort-xyz/iframe:latest
    environment:
      PORT: ${IFRAME_CONTAINER_PORT:-5173}
    networks:
      - db_network
    expose:
      - "5173"
    ports:
      - "${IFRAME_HOST_PORT:-7050}:${IFRAME_CONTAINER_PORT:-5173}"
    depends_on:
      auth_service:
        condition: service_started
        restart: true
    restart: unless-stopped

  iframe-sample:
    container_name: iframe-sample
    build:
      context: ./iframe/sample
      dockerfile: Dockerfile
    image: openfort/iframe-sample:latest
    environment:
      PORT: ${IFRAME_SAMPLE_CONTAINER_PORT:-3000}
    networks:
      - db_network
    expose:
      - "3000"
    ports:
      - "${IFRAME_SAMPLE_HOST_PORT:-7051}:${IFRAME_SAMPLE_CONTAINER_PORT:-3000}"
    depends_on:
      auth_service:
        condition: service_started
        restart: true
      iframe:
        condition: service_started
        restart: true
    restart: unless-stopped

  cold_storage:
    container_name: coldstorage
    platform: linux/amd64
    image: ghcr.io/openfort-xyz/shield:v0.2.30
    command: server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_DRIVER: ${COLD_STORAGE_DB_DRIVER:-mysql}
      DB_NAME: ${COLD_STORAGE_DB_NAME:-shield}
      DB_USER: ${COLD_STORAGE_DB_USER:-root}
      DB_PASS: ${COLD_STORAGE_DB_PASS:-root_password}
      DB_HOST: ${COLD_STORAGE_DB_HOST:-ofmysql}
      DB_PORT: ${COLD_STORAGE_DB_PORT:-3306}
    networks:
      - db_network
    expose:
      - "${COLD_STORAGE_CONTAINER_PORT:-8080}"
    ports:
      - "${COLD_STORAGE_HOST_PORT:-7053}:${HOST_STORAGE_CONTAINER_PORT:-8080}"
    restart: unless-stopped

  docs:
    container_name: docs
    build:
      context: ./docs
      dockerfile: Dockerfile
      args:
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}
    image: openfort/keys-docs:latest
    environment:
      PORT: ${DOCS_CONTAINER_PORT:-4173}
    networks:
      - db_network
    expose:
      - "${DOCS_CONTAINER_:-4173}"
    ports:
      - "${DOCS_HOST_PORT:-7055}:${DOCS_CONTAINER_PORT:-4173}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/health.json"]
      interval: 15s
      timeout: 5s
      retries: 10

networks:
  db_network:
    driver: bridge

volumes:
  of_postgres_data:
  of_mysql_data:
