services:
  iframe:
    container_name: iframe
    platform: linux/amd64
    volumes:
      - ./iframe/iframe_nginx.conf:/etc/nginx/conf.d/default.conf
    image: ghcr.io/openfort-xyz/iframe:latest
    environment:
      PORT: ${IFRAME_CONTAINER_PORT:-5173}
    networks:
      - db_network
    expose:
      - "5173"
    ports:
      - "${IFRAME_HOST_PORT:-7050}:${IFRAME_CONTAINER_PORT:-5173}"
    depends_on:
      auth_service:
        condition: service_started
        restart: true
    restart: unless-stopped

  iframe-sample:
    container_name: iframe-sample
    build:
      context: ./iframe/sample
      dockerfile: Dockerfile
    image: openfort/iframe-sample:latest
    environment:
      PORT: ${IFRAME_SAMPLE_CONTAINER_PORT:-3000}
    networks:
      - db_network
    expose:
      - "3000"
    ports:
      - "${IFRAME_SAMPLE_HOST_PORT:-7051}:${IFRAME_SAMPLE_CONTAINER_PORT:-3000}"
    depends_on:
      auth_service:
        condition: service_started
        restart: true
      iframe:
        condition: service_started
        restart: true
    restart: unless-stopped

  docs:
    container_name: docs
    build:
      context: ./docs
      dockerfile: Dockerfile
      args:
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}
    image: openfort/keys-docs:latest
    environment:
      PORT: ${DOCS_CONTAINER_PORT:-4173}
    networks:
      - db_network
    expose:
      - "${DOCS_CONTAINER_:-4173}"
    ports:
      - "${DOCS_HOST_PORT:-7055}:${DOCS_CONTAINER_PORT:-4173}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/health.json"]
      interval: 15s
      timeout: 5s
      retries: 10

networks:
  db_network:
    driver: bridge
